-- W9 REALTIME & MEDIA — receipts, media metadata and the references that bind them to a room.
--
-- Owner-approved decisions this migration encodes (D1-D5 of the W9 proposal):
--   * Receipts stay AGGREGATE. Each member row gains one high-water mark, `last_delivered_seq`,
--     which is the participant's own statement "my client has received everything up to here
--     over an authenticated channel". There is still no per-message, per-person receipt table
--     and no list of who saw what. A read is always also a delivery, enforced below.
--   * Media METADATA lives in PostgreSQL. The bytes live in an object store behind a port; this
--     table keeps only an opaque `storage_key` that the server generates. No byte column exists
--     here, so the database never holds a file and a backup of it never carries media.
--   * Media belongs to a room exactly as a message does. The composite foreign keys make a
--     media row from another room or another household impossible to store, and the uploader
--     must already be a participant of the room.
--   * No push transport and no FCM state. Realtime is a hint channel; this schema is the truth.
--
-- Everything is additive except one deliberate tightening of the message lifecycle, which now
-- allows a live message with media and no caption. Existing rows satisfy every new rule as they
-- stand, and the backfill below keeps the new receipt invariant true for rows that already exist.

-- ── receipts ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE family_chat_thread_members
  ADD COLUMN last_delivered_seq BIGINT NOT NULL DEFAULT 0 CHECK (last_delivered_seq >= 0);

-- Every read mark recorded so far was taken by a client that had received those messages, so
-- delivery is at least as far as read. Backfilled before the invariant is stated.
UPDATE family_chat_thread_members SET last_delivered_seq = last_read_seq;

ALTER TABLE family_chat_thread_members
  ADD CONSTRAINT family_chat_thread_members_delivered_not_before_read
    CHECK (last_delivered_seq >= last_read_seq);

-- ── media ────────────────────────────────────────────────────────────────────────────────

CREATE TABLE family_chat_media (
  id UUID PRIMARY KEY,
  family_id UUID NOT NULL REFERENCES families(id) ON DELETE RESTRICT,
  thread_id UUID NOT NULL,
  uploader_kind TEXT NOT NULL CHECK (uploader_kind IN ('membership', 'child')),
  uploader_id UUID NOT NULL,
  -- The client's own idempotency key for the upload: a retried upload is the same media.
  client_media_id TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('image', 'audio')),
  -- The type the server SNIFFED from the bytes, never the type the client declared.
  mime_type TEXT NOT NULL CHECK (mime_type IN (
    'image/jpeg', 'image/png', 'image/webp',
    'audio/mp4', 'audio/ogg', 'audio/mpeg')),
  -- Size of the bytes actually stored, after metadata stripping.
  byte_size INTEGER NOT NULL,
  sha256 BYTEA NOT NULL CHECK (octet_length(sha256) = 32),
  -- Client-DECLARED duration of an audio note. It is bounded and labelled as declared; the
  -- server does not decode audio in this release, so it never claims to have measured it.
  declared_duration_ms INTEGER NULL,
  -- Opaque object-store key, generated by the server. Null once the bytes are removed.
  storage_key TEXT NULL CHECK (
    storage_key IS NULL OR storage_key ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'),
  removed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT family_chat_media_thread_fk FOREIGN KEY (family_id, thread_id)
    REFERENCES family_chat_threads (family_id, id) ON DELETE RESTRICT,
  -- Only a participant of the room can put media into it (the same composite-key law messages use).
  CONSTRAINT family_chat_media_uploader_fk FOREIGN KEY (thread_id, uploader_kind, uploader_id)
    REFERENCES family_chat_thread_members (thread_id, participant_kind, participant_id)
    ON DELETE RESTRICT,
  CONSTRAINT family_chat_media_client_unique
    UNIQUE (thread_id, uploader_kind, uploader_id, client_media_id),
  CONSTRAINT family_chat_media_family_thread_id_unique UNIQUE (family_id, thread_id, id),
  CONSTRAINT family_chat_media_client_id_bounded
    CHECK (char_length(client_media_id) BETWEEN 8 AND 64),
  CONSTRAINT family_chat_media_kind_limits CHECK (
    (kind = 'image'
      AND mime_type LIKE 'image/%'
      AND declared_duration_ms IS NULL
      AND byte_size BETWEEN 1 AND 8388608)                 -- 8 MiB
    OR (kind = 'audio'
      AND mime_type LIKE 'audio/%'
      -- NULL must not pass a CHECK, so presence is stated: a voice note always has a declared length.
      AND declared_duration_ms IS NOT NULL
      AND declared_duration_ms BETWEEN 1 AND 300000        -- 5 minutes
      AND byte_size BETWEEN 1 AND 6291456)                 -- 6 MiB
  ),
  -- Bytes exist while the media is live, and only then. Removal keeps the row and its trace.
  CONSTRAINT family_chat_media_lifecycle_complete CHECK (
    (removed_at IS NULL AND storage_key IS NOT NULL)
    OR (removed_at IS NOT NULL AND storage_key IS NULL)
  )
);

-- ── messages carry media ─────────────────────────────────────────────────────────────────

ALTER TABLE family_chat_messages
  ADD COLUMN kind TEXT NOT NULL DEFAULT 'text' CHECK (kind IN ('text', 'image', 'audio')),
  ADD COLUMN media_id UUID NULL,
  ADD CONSTRAINT family_chat_messages_media_fk
    FOREIGN KEY (family_id, thread_id, media_id)
    REFERENCES family_chat_media (family_id, thread_id, id) ON DELETE RESTRICT,
  -- One media, one message: a voice note cannot be attached to two messages.
  ADD CONSTRAINT family_chat_messages_media_once UNIQUE (media_id),
  ADD CONSTRAINT family_chat_messages_kind_matches_media CHECK (
    (kind = 'text' AND media_id IS NULL)
    OR (kind IN ('image', 'audio') AND media_id IS NOT NULL)
  ),
  -- Only text is edited. Media messages keep the bytes they were sent with.
  ADD CONSTRAINT family_chat_messages_edit_text_only CHECK (kind = 'text' OR revision = 1);

ALTER TABLE family_chat_messages DROP CONSTRAINT family_chat_messages_lifecycle_complete;

ALTER TABLE family_chat_messages
  ADD CONSTRAINT family_chat_messages_lifecycle_complete CHECK (
    (deleted_at IS NULL
      AND deleted_by_kind IS NULL
      AND deleted_by_id IS NULL
      AND (body ~ '\S' OR media_id IS NOT NULL))
    OR (deleted_at IS NOT NULL
      AND deleted_by_kind IS NOT NULL
      AND deleted_by_id IS NOT NULL
      AND body = '')
  );
