# -*- coding: utf-8 -*-
from pathlib import Path

ROOT = Path(r"D:/special projects/family/app/lib/core/i18n")


def splice(path: Path, block: str, marker: str) -> None:
    t = path.read_text(encoding="utf-8").rstrip()
    if marker in t:
        print(path.name, "skip", marker)
        return
    body = t[:-1].rstrip()
    if not body.endswith(","):
        body += ","
    path.write_text(body + "\n" + block.strip() + "\n}\n", encoding="utf-8")
    print(path.name, "ok", marker)


EN = r"""
  "familyMomentsTitle": "Our family moments",
  "@familyMomentsTitle": { "description": "SCR-FAT-086 AppBar" },
  "familyMomentsWeekLabel": "Friday · your family's week",
  "@familyMomentsWeekLabel": { "description": "SCR-FAT-086 week" },
  "familyMomentsHeroTitle": "A week worth celebrating!",
  "@familyMomentsHeroTitle": { "description": "SCR-FAT-086 hero" },
  "familyMomentsStatLearn": "learn hrs",
  "@familyMomentsStatLearn": { "description": "SCR-FAT-086 stat" },
  "familyMomentsStatVerses": "verses",
  "@familyMomentsStatVerses": { "description": "SCR-FAT-086 stat" },
  "familyMomentsStatTasks": "tasks done",
  "@familyMomentsStatTasks": { "description": "SCR-FAT-086 stat" },
  "familyMomentsStatAlerts": "worry alerts",
  "@familyMomentsStatAlerts": { "description": "SCR-FAT-086 stat" },
  "familyMomentsStarsTitle": "Star of the week",
  "@familyMomentsStarsTitle": { "description": "SCR-FAT-086 stars" },
  "familyMomentsChildOne": "Child A",
  "@familyMomentsChildOne": { "description": "SCR-FAT-086 Rule 23" },
  "familyMomentsChildTwo": "Child B",
  "@familyMomentsChildTwo": { "description": "SCR-FAT-086 Rule 23" },
  "familyMomentsStarQuran": "{child} — finished Juz Amma!",
  "@familyMomentsStarQuran": {
    "description": "SCR-FAT-086 star",
    "placeholders": { "child": { "type": "String" } }
  },
  "familyMomentsStarQuranSub": "Six months of steady work · a landmark moment",
  "@familyMomentsStarQuranSub": { "description": "SCR-FAT-086 star sub" },
  "familyMomentsStarMath": "{child} — jumped 17% in math",
  "@familyMomentsStarMath": {
    "description": "SCR-FAT-086 star",
    "placeholders": { "child": { "type": "String" } }
  },
  "familyMomentsStarMathSub": "The missing-concept plan paid off",
  "@familyMomentsStarMathSub": { "description": "SCR-FAT-086 star sub" },
  "familyMomentsStarSleep": "{child} — a full week of steady sleep",
  "@familyMomentsStarSleep": {
    "description": "SCR-FAT-086 star",
    "placeholders": { "child": { "type": "String" } }
  },
  "familyMomentsStarSleepSub": "First time in two months",
  "@familyMomentsStarSleepSub": { "description": "SCR-FAT-086 star sub" },
  "familyMomentsShareCta": "Share pride card with the family",
  "@familyMomentsShareCta": { "description": "SCR-FAT-086 share" },
  "familyMomentsPrideToast": "Pride card reached family chat — they saw your applause!",
  "@familyMomentsPrideToast": { "description": "SCR-FAT-086 pride toast" },
  "familyMomentsTouchTitle": "Next week's touch",
  "@familyMomentsTouchTitle": { "description": "SCR-FAT-086 touch" },
  "familyMomentsTouchBody": "Child B is close to finishing Surah Al-Mulk — when they do, how about a surprise outing they choose? Deeper than any minutes reward.",
  "@familyMomentsTouchBody": { "description": "SCR-FAT-086 touch body" },
  "familyMomentsTouchCta": "Love it — remind me",
  "@familyMomentsTouchCta": { "description": "SCR-FAT-086 touch CTA" },
  "familyMomentsTouchToast": "Surprise promised — you'll get a reminder when the surah is done",
  "@familyMomentsTouchToast": { "description": "SCR-FAT-086 touch toast" },
  "familyMomentsAlbumTitle": "Moments album",
  "@familyMomentsAlbumTitle": { "description": "SCR-FAT-086 album" },
  "familyMomentsCapGarden": "Garden day",
  "@familyMomentsCapGarden": { "description": "SCR-FAT-086 cap" },
  "familyMomentsCapPrayer": "Fajr together",
  "@familyMomentsCapPrayer": { "description": "SCR-FAT-086 cap" },
  "familyMomentsCapCook": "Helped cook",
  "@familyMomentsCapCook": { "description": "SCR-FAT-086 cap" },
  "familyMomentsCapRead": "Story night",
  "@familyMomentsCapRead": { "description": "SCR-FAT-086 cap" },
  "familyMomentsCapWalk": "Evening walk",
  "@familyMomentsCapWalk": { "description": "SCR-FAT-086 cap" },
  "familyMomentsCapLaugh": "Family laugh",
  "@familyMomentsCapLaugh": { "description": "SCR-FAT-086 cap" },
  "familyMomentsCapNew": "New moment",
  "@familyMomentsCapNew": { "description": "SCR-FAT-086 cap" },
  "familyMomentsByMother": "Mother",
  "@familyMomentsByMother": { "description": "SCR-FAT-086 by" },
  "familyMomentsByFather": "Father",
  "@familyMomentsByFather": { "description": "SCR-FAT-086 by" },
  "familyMomentsWhenYesterday": "yesterday",
  "@familyMomentsWhenYesterday": { "description": "SCR-FAT-086 when" },
  "familyMomentsWhenTue": "Tue",
  "@familyMomentsWhenTue": { "description": "SCR-FAT-086 when" },
  "familyMomentsWhenMon": "Mon",
  "@familyMomentsWhenMon": { "description": "SCR-FAT-086 when" },
  "familyMomentsWhenSun": "Sun",
  "@familyMomentsWhenSun": { "description": "SCR-FAT-086 when" },
  "familyMomentsWhenSat": "Sat",
  "@familyMomentsWhenSat": { "description": "SCR-FAT-086 when" },
  "familyMomentsWhenFri": "Fri",
  "@familyMomentsWhenFri": { "description": "SCR-FAT-086 when" },
  "familyMomentsWhenNow": "now",
  "@familyMomentsWhenNow": { "description": "SCR-FAT-086 when" },
  "familyMomentsAddCta": "+ Add a moment",
  "@familyMomentsAddCta": { "description": "SCR-FAT-086 add" },
  "familyMomentsAddToast": "Added to moments — family notified",
  "@familyMomentsAddToast": { "description": "SCR-FAT-086 add toast" },
  "familyMomentsFridayBanner": "Arrives every Friday morning — open, celebrate, share. Then rest easy.",
  "@familyMomentsFridayBanner": { "description": "SCR-FAT-086 banner" },
  "familyMomentsEmptyTitle": "No family moments yet",
  "@familyMomentsEmptyTitle": { "description": "SCR-FAT-086 empty" },
  "familyMomentsEmptyMessage": "Add a child so weekly pride, stars, and the moments album can light up.",
  "@familyMomentsEmptyMessage": { "description": "SCR-FAT-086 empty msg" },
  "familyMomentsEmptyCta": "Add a child",
  "@familyMomentsEmptyCta": { "description": "SCR-FAT-086 →003" },
  "familyMomentsLoadingSemantics": "Loading family moments",
  "@familyMomentsLoadingSemantics": { "description": "SCR-FAT-086 loading" },
  "familyMomentsChildLeanTitle": "Family moments",
  "@familyMomentsChildLeanTitle": { "description": "SCR-FAT-086 child lean" },
  "familyMomentsChildLeanMessage": "Parents open the weekly pride wrap. Your stars show up in My learning.",
  "@familyMomentsChildLeanMessage": { "description": "SCR-FAT-086 child lean msg" }
"""

AR = r"""
  "familyMomentsTitle": "لحظات عائلتنا",
  "@familyMomentsTitle": { "description": "SCR-FAT-086 AppBar" },
  "familyMomentsWeekLabel": "جمعة · أسبوع عائلتكم",
  "@familyMomentsWeekLabel": { "description": "SCR-FAT-086 week" },
  "familyMomentsHeroTitle": "أسبوع يستحق الفخر!",
  "@familyMomentsHeroTitle": { "description": "SCR-FAT-086 hero" },
  "familyMomentsStatLearn": "ساعة تعلّم",
  "@familyMomentsStatLearn": { "description": "SCR-FAT-086 stat" },
  "familyMomentsStatVerses": "آية حُفظت",
  "@familyMomentsStatVerses": { "description": "SCR-FAT-086 stat" },
  "familyMomentsStatTasks": "مهمة أُنجزت",
  "@familyMomentsStatTasks": { "description": "SCR-FAT-086 stat" },
  "familyMomentsStatAlerts": "تنبيه مقلق",
  "@familyMomentsStatAlerts": { "description": "SCR-FAT-086 stat" },
  "familyMomentsStarsTitle": "نجم الأسبوع",
  "@familyMomentsStarsTitle": { "description": "SCR-FAT-086 stars" },
  "familyMomentsChildOne": "الابن أ",
  "@familyMomentsChildOne": { "description": "SCR-FAT-086 Rule 23" },
  "familyMomentsChildTwo": "الابن ب",
  "@familyMomentsChildTwo": { "description": "SCR-FAT-086 Rule 23" },
  "familyMomentsStarQuran": "{child} — أنهى جزء عمّ كاملًا!",
  "@familyMomentsStarQuran": {
    "description": "SCR-FAT-086 star",
    "placeholders": { "child": { "type": "String" } }
  },
  "familyMomentsStarQuranSub": "٦ أشهر من المثابرة · لحظة تاريخية",
  "@familyMomentsStarQuranSub": { "description": "SCR-FAT-086 star sub" },
  "familyMomentsStarMath": "{child} — قفز ١٧٪ في الرياضيات",
  "@familyMomentsStarMath": {
    "description": "SCR-FAT-086 star",
    "placeholders": { "child": { "type": "String" } }
  },
  "familyMomentsStarMathSub": "خطة «المفهوم المفقود» أثمرت",
  "@familyMomentsStarMathSub": { "description": "SCR-FAT-086 star sub" },
  "familyMomentsStarSleep": "{child} — أسبوع كامل نوم منتظم",
  "@familyMomentsStarSleep": {
    "description": "SCR-FAT-086 star",
    "placeholders": { "child": { "type": "String" } }
  },
  "familyMomentsStarSleepSub": "أول مرة منذ شهرين",
  "@familyMomentsStarSleepSub": { "description": "SCR-FAT-086 star sub" },
  "familyMomentsShareCta": "شارك بطاقة الفخر مع العائلة",
  "@familyMomentsShareCta": { "description": "SCR-FAT-086 share" },
  "familyMomentsPrideToast": "وصلت بطاقة الفخر لمحادثة العائلة — شافوا تصفيقكم!",
  "@familyMomentsPrideToast": { "description": "SCR-FAT-086 pride toast" },
  "familyMomentsTouchTitle": "لمسة الأسبوع القادم",
  "@familyMomentsTouchTitle": { "description": "SCR-FAT-086 touch" },
  "familyMomentsTouchBody": "الابن ب اقترب من إنهاء سورة الملك — لو أنهاها، ما رأيك بمفاجأة «مشوار يختاره هو»؟ الأثر أعمق من أي دقائق.",
  "@familyMomentsTouchBody": { "description": "SCR-FAT-086 touch body" },
  "familyMomentsTouchCta": "أُحب الفكرة — ذكّرني",
  "@familyMomentsTouchCta": { "description": "SCR-FAT-086 touch CTA" },
  "familyMomentsTouchToast": "وُعدت المفاجأة — سيصلك تذكير عند إتمام السورة",
  "@familyMomentsTouchToast": { "description": "SCR-FAT-086 touch toast" },
  "familyMomentsAlbumTitle": "ألبوم اللحظات",
  "@familyMomentsAlbumTitle": { "description": "SCR-FAT-086 album" },
  "familyMomentsCapGarden": "يوم الحديقة",
  "@familyMomentsCapGarden": { "description": "SCR-FAT-086 cap" },
  "familyMomentsCapPrayer": "فجر معًا",
  "@familyMomentsCapPrayer": { "description": "SCR-FAT-086 cap" },
  "familyMomentsCapCook": "ساعد في الطبخ",
  "@familyMomentsCapCook": { "description": "SCR-FAT-086 cap" },
  "familyMomentsCapRead": "ليلة قصة",
  "@familyMomentsCapRead": { "description": "SCR-FAT-086 cap" },
  "familyMomentsCapWalk": "مشية مسائية",
  "@familyMomentsCapWalk": { "description": "SCR-FAT-086 cap" },
  "familyMomentsCapLaugh": "ضحكة عائلية",
  "@familyMomentsCapLaugh": { "description": "SCR-FAT-086 cap" },
  "familyMomentsCapNew": "لحظة جديدة",
  "@familyMomentsCapNew": { "description": "SCR-FAT-086 cap" },
  "familyMomentsByMother": "الأم",
  "@familyMomentsByMother": { "description": "SCR-FAT-086 by" },
  "familyMomentsByFather": "الأب",
  "@familyMomentsByFather": { "description": "SCR-FAT-086 by" },
  "familyMomentsWhenYesterday": "أمس",
  "@familyMomentsWhenYesterday": { "description": "SCR-FAT-086 when" },
  "familyMomentsWhenTue": "ثلاثاء",
  "@familyMomentsWhenTue": { "description": "SCR-FAT-086 when" },
  "familyMomentsWhenMon": "اثنين",
  "@familyMomentsWhenMon": { "description": "SCR-FAT-086 when" },
  "familyMomentsWhenSun": "أحد",
  "@familyMomentsWhenSun": { "description": "SCR-FAT-086 when" },
  "familyMomentsWhenSat": "سبت",
  "@familyMomentsWhenSat": { "description": "SCR-FAT-086 when" },
  "familyMomentsWhenFri": "جمعة",
  "@familyMomentsWhenFri": { "description": "SCR-FAT-086 when" },
  "familyMomentsWhenNow": "الآن",
  "@familyMomentsWhenNow": { "description": "SCR-FAT-086 when" },
  "familyMomentsAddCta": "+ أضف لحظة",
  "@familyMomentsAddCta": { "description": "SCR-FAT-086 add" },
  "familyMomentsAddToast": "أُضيفت للحظات — وأُخطرت العائلة",
  "@familyMomentsAddToast": { "description": "SCR-FAT-086 add toast" },
  "familyMomentsFridayBanner": "يصلك كل جمعة صباحًا — افتح، افرح، شارك. ثم أغلق مطمئنًا.",
  "@familyMomentsFridayBanner": { "description": "SCR-FAT-086 banner" },
  "familyMomentsEmptyTitle": "لا لحظات عائلية بعد",
  "@familyMomentsEmptyTitle": { "description": "SCR-FAT-086 empty" },
  "familyMomentsEmptyMessage": "أضف ابنًا ليضيء ملخص الفخر الأسبوعي ونجوم الأسبوع وألبوم اللحظات.",
  "@familyMomentsEmptyMessage": { "description": "SCR-FAT-086 empty msg" },
  "familyMomentsEmptyCta": "أضف ابنًا",
  "@familyMomentsEmptyCta": { "description": "SCR-FAT-086 →003" },
  "familyMomentsLoadingSemantics": "جاري تحميل لحظات العائلة",
  "@familyMomentsLoadingSemantics": { "description": "SCR-FAT-086 loading" },
  "familyMomentsChildLeanTitle": "لحظات العائلة",
  "@familyMomentsChildLeanTitle": { "description": "SCR-FAT-086 child lean" },
  "familyMomentsChildLeanMessage": "الوالدان يفتحان ملخص الفخر الأسبوعي. نجومك تظهر في تعلّمي.",
  "@familyMomentsChildLeanMessage": { "description": "SCR-FAT-086 child lean msg" }
"""

if __name__ == "__main__":
    splice(ROOT / "app_en.arb", EN, "familyMomentsTitle")
    splice(ROOT / "app_ar.arb", AR, "familyMomentsTitle")
